apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service

spec:
  type: ClusterIP
  selector:
    component: redis-cluster
  ports:
    - port: 6379 #clusterport
      targetPort: 6379 #container port of the target to which to be routed
  